title: Project Nexus Docs
description: Documentation des scripts, mappings et ressources FiveM de Project Nexus

url: "https://pn-projectnexus.github.io"
baseurl: "/pn_docs"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: "categories"
    values:
      layout: page
  - scope:
      path: ""
      type: pages
    values:
      layout: default

permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore
